# Generated by Django 3.1.5 on 2021-02-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20210113_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['titulo', 'publicado'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default='null', upload_to='articulos', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='publicado',
            field=models.BooleanField(verbose_name='¿Publicado?'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
    ]
